### ISSUE TITLE
Make error on TX1 

### ISSUE THREAD

**Issue by shuyu0815** [NVIDIA/caffe#393] opened 2017-08-08 17:10 UTC
I try to build nvcaffe 0.16 on jetson TX1 (with jetpack 3.1), but I got the error ## "/usr/bin/ld: cannot find -lnvidia-ml" 

I saw someone has installed in TX1 successfully, I think I could make some mistakes in installation ！
Please give some suggestions! 

Thanks for help !

**Comment by drnikolaev** [comment] 2017-08-08 22:48
Hi @shuyu0815 I got similar error but while running, not linking. Thanks for reporting.
While I'm working on the fix for this issue please use the following workaround (you might need to rebuild NVCaffe because `link` should succeed no matter what):
```
sudo apt-get install cmake
sudo apt-get install build-essential
sudo apt-get install libboost-all-dev
sudo apt-get install protobuf-compiler
sudo apt-get install hdf5-tools
sudo apt-get install hdf5-helpers
sudo apt-get install libhdf5-dev
sudo apt-get install libgflags-dev
sudo apt-get install libprotobuf-dev
sudo apt-get install libgoogle-glog-dev
sudo apt-get install liblmdb-dev
sudo apt-get install libleveldb-dev
sudo apt-get install libsnappy-dev
sudo apt-get install libatlas-base-dev
sudo apt-get install libatlas-dev

caffe_dir$ mkdir build
caffe_dir$ cd build
caffe_dir/build$ cmake -DCMAKE_BUILD_TYPE=Release -DTEST_FP16=ON -DUSE_CUDNN=ON -DCPU_ONLY=OFF -G "Unix Makefiles" ..
caffe_dir/build$ make -j4
caffe_dir/build$ make -j4 test.testbin
caffe_dir/build$ cd ..

caffe_dir$ sudo ln -s /usr/local/cuda-8.0/targets/aarch64-linux/lib/stubs/libnvidia-ml.so /usr/local/cuda-8.0/targets/aarch64-linux/lib/stubs/libnvidia-ml.so.1
caffe_dir$ export LD_LIBRARY_PATH=/usr/local/cuda-8.0/targets/aarch64-linux/lib/stubs
```

Then try to run tests:

```
caffe_dir$ ./build/test/test.testbin-d 
Cuda number of devices: 1
Current device id: 0
Current device name: NVIDIA Tegra X1
I0808 15:33:55.205299 21827 gpu_memory.cpp:159] GPUMemory::Manager initialized with Caching (CUB) GPU Allocator
I0808 15:33:55.206938 21827 gpu_memory.cpp:161] Total memory: 4176248832, Free: 1505189888, dev_info[0]: total=4176248832 free=1505189888
[==========] Running 2670 tests from 365 test cases.
[----------] Global test environment set-up.
[----------] 9 tests from CPUMathFunctionsTest/0, where TypeParam = float
[ RUN      ] CPUMathFunctionsTest/0.TestNothing
I0808 15:33:55.275024 21827 common.cpp:228] New stream 0x483de40 on device 0, thread 548120567808
[       OK ] CPUMathFunctionsTest/0.TestNothing (102 ms)
[ RUN      ] CPUMathFunctionsTest/0.TestAlign
[       OK ] CPUMathFunctionsTest/0.TestAlign (40 ms)
[ RUN      ] CPUMathFunctionsTest/0.TestHammingDistance
[       OK ] CPUMathFunctionsTest/0.TestHammingDistance (44 ms)
[ RUN      ] CPUMathFunctionsTest/0.TestAsum
[       OK ] CPUMathFunctionsTest/0.TestAsum (41 ms)
```

**Comment by shuyu0815** [comment] 2017-08-09 09:23
Thanks for your reply !

It runs OK but I got some error in runtest ! 
and there are OK ?

<img width="790" alt="2017-08-09 3 42 38" src="https://user-images.githubusercontent.com/20681245/29114541-3ea7693c-7d27-11e7-91c6-72ca48311785.png">

Thanks for help !

**Comment by drnikolaev** [comment] 2017-08-09 21:38
@shuyu0815 you may safely ignore those failures. They are caused by OpenCV's double precision glitch. I'll remove them in next release.

**Comment by shuyu0815** [comment] 2017-08-10 05:27
Thanks you !

**Comment by drnikolaev** [comment] 2017-08-11 03:04
Fixed.

**Closed as completed by drnikolaev** 2017-08-11 03:04 UTC
Labels: bug
