### ISSUE TITLE
Repeatedly calling Solver::Step(1) leads to a memory leak (0.17)

### ISSUE THREAD

**Issue by seanbell** [NVIDIA/caffe#459] opened 2018-01-04 00:31 UTC
I'm trying out 0.16.5, and while it seems to work great in terms of memory/speed, there is still a memory leak when training by repeatedly calling `solver.step(1)` (i.e.`Solver::Step(1)`) in a loop.  When training using a Python framework, this is the only way to train and also get per-iteration statistics.  Memory usage slowly increases by around 1-2MB per iteration.

In a previous release, I determined a fix (https://github.com/NVIDIA/caffe/pull/427), but those variables are no longer present, and it seems like there is a different memory leak now.

Have you tested this configuration? @drnikolaev 

I also see this printed every iteration, which seems suspicious:
```
I0104 00:21:09.116499  1263 net.cpp:1408] [0] Reserving 289082112 bytes of shared learnable space for type FLOAT
```
Is there a reason why we need to re-allocate all variables every solver step?  Can we just call `net_->InitializeLearnableDiffSpace(type_id);` on the first iteration only, rather than on every iteration?

(I am using 0.16.5, 1 GPU, cuDNN v6, CUDA 8)

Thanks for your help!
Sean

**Comment by drnikolaev** [comment] 2018-01-04 08:11
Hi @seanbell 
Seems like this issue is Python-related only. Valgrind is happy. Would you mind to send small isolated script reproducing the leak?

**Comment by nalan210** [comment] 2018-01-04 12:22
@drnikolaev @seanbell  Excuse me, I am a newcomer for the nvidia/caffe. Now I want to install this latest caffe version(0.16), how could I achieve the setup and tune the inference process to support FP16 instead of FP32?

**Comment by drnikolaev** [comment] 2018-01-05 03:15
@seanbell I can't reproduce this. When I add this test to `python/caffe/test/test_solver.py`:
```
    def test_step(self):
        p = psutil.Process()
        for i in range(10000):
            self.assertEqual(self.solver.iter, i)
            self.solver.step(1)
            if (i % 100 == 0):
                print(p.name() + " ************ " + str(p.memory_full_info().uss))
```
it prints identical memory usage 100 times.

**Comment by seanbell** [comment] 2018-01-05 21:03
Hi @drnikolaev -- thank you for running the tests and looking into this, confirming that `solver.step(1)` works as expected.  We currently suspect that this may in fact be an issue with our code, and not `NVIDIA/caffe`, so I am going to close this for now, and will re-open if we discover other issues.

**Comment by drnikolaev** [comment] 2018-01-05 22:59
@seanbell thanks. There is always room for improvement though: 1000 Step(1) calls created 1000 instances of Caffe class. Fixed here: https://github.com/drnikolaev/caffe/tree/caffe-0.16
Release coming soon.

**Comment by gomlgs** [comment] 2018-07-19 18:14
@drnikolaev I ran your test from the comment on Jan 4 (the commented out bits in test_solver.py) and I now see a steady increase in 0.17. Can you take a look?

```
python ************ 1430331392
python ************ 1451675648
python ************ 1473810432
python ************ 1495957504
python ************ 1518088192
```

This is with caffe 0.17, CUDA 9+cudnn7
```
$ nvidia-smi
Thu Jul 19 18:33:57 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.81                 Driver Version: 384.81                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:1E.0 Off |                    0 |
| N/A   35C    P0    25W / 300W |      0MiB / 16152MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by gomlgs** [comment] 2018-08-14 19:02
@drnikolaev Hey Sergei - any update on this? We'd love to get back to using 0.17.

**Comment by drnikolaev** [comment] 2018-08-20 21:11
@seanbell so, latest https://github.com/drnikolaev/caffe/tree/caffe-0.17 still affected? hmm, may I ask you to try Anaconda?

**Comment by gomlgs** [comment] 2018-08-20 21:15
I'll try your tree and get back to you. Note that I was running the test you added in https://github.com/NVIDIA/caffe/issues/459#issuecomment-355462672

**Comment by gomlgs** [comment] 2018-08-20 23:13
Using https://github.com/drnikolaev/caffe/tree/caffe-0.17:
```
python ************ 621797376
python ************ 631488512
python ************ 640012288
python ************ 648544256
python ************ 657055744
```
So, yes, the issue is still ongoing. @drnikolaev

**Comment by drnikolaev** [comment] 2018-08-22 02:01
@gomlgs @seanbell Reproduced&fixed in https://github.com/drnikolaev/caffe/tree/caffe-0.17

**Closed as completed by drnikolaev** 2018-08-22 02:01 UTC

**Comment by gomlgs** [comment] 2018-08-22 03:39
Fantastic, thank you!
