### ISSUE TITLE
caffe 0.16 keeps hanging

### ISSUE THREAD

**Issue by RSly** [NVIDIA/caffe#315] opened 2017-04-28 05:39 UTC
Hi,

I have seen this multiple times now that the training hangs after a couple of hours.
I am using caffe 0.16, cudnn 6, cuda 7.5 under ubuntu and train with 3 gpus.

How can I debug this? 
is there a special logging mechanism for this case? there is no message, the GPU RAM is used as it should, but GPU usages are at 0

also impossible to do ctr+C to kill it, and should be killed via top/kill function

here is the last message and hours later nothing new came out
I0427 21:09:09.712353  5604 sgd_solver.cpp:108] Iteration 299, lr = 0.000207384

**Comment by drnikolaev** [comment] 2017-04-28 06:29
@RSly thanks for reporting. I fixed Ctrl-C issue and Testing phase hang, please pull the latest code base and retry. If problem still exists, please attach full log.

**Comment by RSly** [comment] 2017-04-28 07:15
Thanks,
this has also been reported in https://github.com/BVLC/caffe/issues/1412

based on that discussion I temporarily put /proc/sys/vm/swappiness to zero
I will try the update then.

**Comment by RSly** [comment] 2017-04-29 12:46
hi @drnikolaev 
the problem still exist.
the hanging iteration is random 
I have tested it multiple times. there is nothing more in the log
is there any method to log the stack etc. when the gpu usage becomes 0 for hours?

**Comment by drnikolaev** [comment] 2017-04-29 16:12
Hi @RSly 
I need to reproduce this. What model do you run? What dataset?

**Comment by RSly** [comment] 2017-04-30 10:59
alexnet fcn and the weights from the segmentation example + voc python layer from https://github.com/shelhamer/fcn.berkeleyvision.org/blob/master/voc_layers.py

**Comment by RSly** [comment] 2017-05-02 07:23
hi @drnikolaev
did you succeed to reproduce the problem?
the other day I launched two similar tasks on separate gpus to test this again, one task was hanging for a day, the other didnt hang, up to now...
I am wondering since it was similar architecture, similar data and loss layers, etc.! 
=> can it be related to the numerical values of loss and lr?
=> maybe it could be a good idea to catch these hanging cases by monitoring the GPU activity as shown in nvidia-smi

**Comment by drnikolaev** [comment] 2017-05-03 06:54
@RSly still no luck, sorry. Meanwhile, we did one fix which might be related to the problem you reported. Could you try it please?

**Comment by RSly** [comment] 2017-05-03 07:05
Thanks,, I will try it.
From my side, it is a frequent hang, if it is still there, I will make a minimal test example for you

**Comment by drnikolaev** [comment] 2017-05-03 07:06
@RSly oh, that would help a lot, thank you.

**Comment by RSly** [comment] 2017-05-04 09:32
Hi @drnikolaev 
I could isolate a reproducible case, using digits segmentation task from here
https://github.com/NVIDIA/DIGITS/tree/master/examples/medical-imaging

and the dice loss layer from here
https://github.com/faustomilletari/VNet/blob/master/pyLayer.py

it ends up hanging very often (sooner or later depending on the lr and other parameters)

**Comment by RSly** [comment] 2017-05-04 17:01
ok @drnikolaev as promised I created a small hanging case for you
1. run the attached create_images. out of the box, it will create 1489 rgb images of (3,1200,1920) and Palette labels of (1,1200,1920)
[create_images.txt](https://github.com/NVIDIA/caffe/files/976943/create_images.txt)
2. digits > datasets >new dataset > segmentation, add input and target paths, leave all other fields as default, also color map from label image
3. use the attached job folder of the training + pretrained model from examples/semantic-segmentation/fcn_alexnet.caffemodel + 2 gpus  
[20170504-185354-480f.zip](https://github.com/NVIDIA/caffe/files/976969/20170504-185354-480f.zip)

run the training multiple times, it should freeze after some iterations

**Comment by mathmanu** [comment] 2017-05-05 13:38
For me the hang is in the very first training iteration itself. But if I replace the data layer with a python layer, it doesn't hang (but since it's too slow I cannot use it). 

This hang is observed in caffe-0.16. (caffe-0.15 does not hang).

I am attaching the prototxt (solver+train) that causes the hang:
[net11(1000)_bn_maxpool_train_L2.zip](https://github.com/NVIDIA/caffe/files/979186/net11.1000._bn_maxpool_train_L2.zip)

Kindly help.

**Comment by drnikolaev** [comment] 2017-05-05 15:23
@RSly  Thank you for your help! I did reproduce one hang some time ago and fixed it here: #325 
Could you try it please?

@mathmanu - while I'm checking your model, please try to add:
```
data_param {
    ...
    threads: N
    parser_threads: M
}
```
where M=1,...,4 and N=1,...,4

**Comment by drnikolaev** [comment] 2017-05-08 04:26
@mathmanu I reproduced the hang you reported, thank you. It's now fixed.

**Comment by mathmanu** [comment] 2017-05-08 11:09
@drnikolaev Thankyou for the fix. I have tried it and it is no longer hanging.

I  have couple of observations:

1. The test phase in the beginning seems to be coming out very fast after doing just one iteration or so. Even if I increase the test_iter to a very large number, the same thing happens. This behavior was same even before the fix that you did.

2. I tried to use in-place BatchNorm (which was not training in caffe-0.15, but seems to have been fixed in caffe-0.16). I did this and it seems to be consuming more GPU memory than using separate blob for BatchNorm output. It seems surprising that in-place consumes more memory.

3. I I enable the following:
default_forward_type:  FLOAT16
default_backward_type: FLOAT16
I get a crash with the following trace:
F0508 17:37:11.442492 27910 blob.cpp:346] Trying to copy blobs of different sizes.
*** Check failure stack trace: ***
    @     0x7fd27dcbbdaa  (unknown)
    @     0x7fd27dcbbce4  (unknown)
    @     0x7fd27dcbb6e6  (unknown)
    @     0x7fd27dcbe687  (unknown)
    @     0x7fd27e5682f3  caffe::Blob::CopyFrom()
    @     0x7fd27e84a828  caffe::CuDNNBatchNormLayer<>::Backward_gpu()
F0508 17:37:11.451145 27911 blob.cpp:346] Trying to copy blobs of different sizes.
*** Check failure stack trace: ***
    @     0x7fd27e53aa1d  caffe::Layer<>::Backward()
    @     0x7fd27dcbbdaa  (unknown)
    @     0x7fd27e570d39  caffe::Net::BackwardFromToAu()
    @     0x7fd27dcbbce4  (unknown)
    @     0x7fd27dcbb6e6  (unknown)
    @     0x7fd27e571045  caffe::Net::Backward()
    @     0x7fd27dcbe687  (unknown)
    @     0x7fd27e5712c1  caffe::Net::ForwardBackward()
    @     0x7fd27e5682f3  caffe::Blob::CopyFrom()
    @     0x7fd27e5357c8  caffe::Solver::Step()
    @     0x7fd27e84a828  caffe::CuDNNBatchNormLayer<>::Backward_gpu()
    @     0x7fd27e536540  caffe::Solver::Solve()
    @     0x7fd27e53aa1d  caffe::Layer<>::Backward()
    @     0x7fd27e57f7bb  caffe::P2PSync::InternalThreadEntry()
    @     0x7fd27e570d39  caffe::Net::BackwardFromToAu()
    @     0x7fd27e5b1062  caffe::InternalThread::entry()
    @     0x7fd27e571045  caffe::Net::Backward()
    @     0x7fd27e5b1cb4  boost::detail::thread_data<>::run()
    @     0x7fd27e5712c1  caffe::Net::ForwardBackward()
    @     0x7fd27381ae7a  (unknown)
    @     0x7fd27c0c1184  start_thread
    @     0x7fd27e5357c8  caffe::Solver::Step()
    @     0x7fd27c5efbed  (unknown)
    @     0x7fd27e536540  caffe::Solver::Solve()
    @              (nil)  (unknown)

**Comment by RSly** [comment] 2017-05-08 12:09
hi @drnikolaev I will test the update soon for hangs

also I agree with @mathmanu that the first test is too fast and basically wrong values come out: often in the iteration 0 of test, **the loss is almost zero (which is wrong)** and then it jumps to its correct value around 1 and then starts reducing through time as it should
maybe Test 0 was not intended to be a Test but more of an initialization phase??

**Comment by RSly** [comment] 2017-05-09 11:45
hi @drnikolaev regarding the hanging:
1. I ran a set of tests, and I can confirm that the early hangs are solved. I will run over longer time periods and see the behavior.

2. I notice a considerable drop in speed in the latest version: before, each iteration would took ~12 sec in average, now the average is up to ~50 second: some iteration remain at ~12 sec but many others jump up to 60-80 seconds, examples here:

Iteration 278 (0.087832 iter/s, **11.3854s/1 iter**), loss = 3.5056
Iteration 279 (0.0810425 iter/s, **12.3392s/1 iter**), loss = 3.28147
Iteration 280 (0.0835199 iter/s, **11.9732s/1 iter**), loss = 3.52662
Iteration 281 (0.0151576 iter/s, **65.9734s/1 iter**), loss = 3.24131
Iteration 282 (0.0131568 iter/s, **76.0061s/1 iter**), loss = 3.26729
Iteration 283 (0.0129066 iter/s, **77.48s/1 iter**), loss = 3.84125

could you please take a look at the drop in speed? thanks

3. [Critical BUG]: @drnikolaev, with the new update, I get a systematic memory error for inference of my new or old models!! also same thing when using digits infere one (i.e digits/digits/tools/inference.py). This is independent of my input image size

WARNING: Logging before InitGoogleLogging() is written to STDERR
F0509 16:00:58.559514 23815 gpu_memory.cpp:286] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***


=>actually just the following three lines makes a fatal memory error ;)
**import caffe
caffe.set_mode_gpu()
caffe.set_device(0)**

**Comment by drnikolaev** [comment] 2017-05-10 02:10
@mathmanu 
1. First test is for init purpose, it doesn't print redundant values any longer.
2. BN has internal buffer now, it takes some extra space.
3. I can't reproduce this. Are you reading from FP32 snapshot?..

@RSly 
1. Cool, thnx
2. Well, Python 2 needs special care in parallel environments, so I had to guard some calls by critical sections. Python 3 is better in this sense but it will require some work..
3. Fixed by #332 - now you can just say: `caffe.set_device(0)` or `caffe.set_devices([0,1,2])`

**Comment by RSly** [comment] 2017-05-10 10:01
1. @drnikolaev thanks for the updates. No hang after 20hours, so it is good news! we can close this hang issue, and I hope hangs never come back to caffe!

2. One quick question, the loss and accuracy values that are printed, for multi-gpu case, are calculated over all the results from all the gpus and aggregated to one single value, right?
in other words, the loss value is not printed for each GPU but it is the final loss considering all the batches in all the GPUs?

3. @drnikolaev, I noticed that the Iteration 0 test printing should be completely disabled or should print all the outputs, otherwise it breaks the log_parser.py! in the latest version, the loss outputs are removed from iteration 0 Test, but all other custom outputs or for example accuracy will be printed. in return this breaks the log_parser since it reads its dict keys from the incomplete iteration 0 outputs, and then in other iterations it sees more outputs.
Refer to:  dict_writer = csv.DictWriter(f, fieldnames=dict_list[0].keys(), dialect=dialect)

**Comment by mathmanu** [comment] 2017-05-11 05:29
@drnikolaev Thankyou for the clarifications. 

Testing at the beginning of training was a nice feature. (it used to print the correct loss and accuracy values - quite useful when finetuning the same model with slightly different solver parameters). Can we have this feature back?

**Comment by drnikolaev** [comment] 2017-05-11 06:15
@mathmanu It's back and it now prints correct loss

@RSly 
2. Aggregated
3. It now prints everything like it used to

As of PythonLayer performance, we did some improvements today and we'd appreciate your feedback.

**Comment by RSly** [comment] 2017-05-12 09:18
hi @drnikolaev, unfortunately with the last update the hang is back for the same tests as before.

**Comment by drnikolaev** [comment] 2017-05-12 15:22
@RSly hmm, is this the same https://github.com/NVIDIA/DIGITS/tree/master/examples/medical-imaging or something else?

**Comment by RSly** [comment] 2017-05-12 16:25
hi @drnikolaev, yes, it is the same type of hang as before, even earlier this time.
you can reproduce it using  https://github.com/NVIDIA/DIGITS/tree/master/examples/medical-imaging  or definitely in https://github.com/NVIDIA/caffe/issues/315#issuecomment-299246892

* I went back to this commit,  
 Merge pull request #333 from drnikolaev/caffe-0.16 
and there is no hang there, so it is coming from commits of May 11, 2017

**Comment by drnikolaev** [comment] 2017-05-14 21:04
Hi @RSly, thank you. #334 should return things back to normal. Let me close this issue. If something is still broken please open a new one.

**Closed as completed by drnikolaev** 2017-05-14 21:04 UTC
Labels: bug
